# Generated by Django 6.0.1 on 2026-05-07 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("my_brain", "0002_knowledgechunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "car_name",
                    models.CharField(
                        max_length=255, verbose_name="車種名 (例: Porsche 911 Carrera)"
                    ),
                ),
                (
                    "hero_images",
                    models.JSONField(
                        default=list, verbose_name="LP用メイン画像URLリスト"
                    ),
                ),
                (
                    "generated_story",
                    models.TextField(
                        blank=True, null=True, verbose_name="AI生成ストーリー"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "下書き（AI処理中・確認待ち）"),
                            ("PUBLISHED", "公開中（LPとしてアクセス可能）"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="my_brain.chatlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "車両LPデータ",
                "verbose_name_plural": "車両LPデータ一覧",
                "ordering": ["-created_at"],
            },
        ),
    ]
