"""
Django settings for car_shop project.

Generated by 'django-admin startproject' using Django.
"""

from pathlib import Path
import os  # ★追加：パス操作に必要です

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# ★本番公開時は、このキーは他人に見せないでください
SECRET_KEY = 'django-insecure-change-me-please-make-this-unique-and-secret'

# SECURITY WARNING: don't run with debug turned on in production!
# ★本番環境なので False にします（エラー画面でコードが見えないようにするため）
DEBUG = True

# ★最初はすべて許可にしておきます（後で 'yourname.pythonanywhere.com' に限定も可）
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cars',  # ★あなたのアプリ（忘れず記述）
    # ★この1行を追加してください！
    'django.contrib.humanize',
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ←★この1行を追加！（カンマを忘れずに）
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # HTMLテンプレートフォルダがある場合はここに os.path.join(BASE_DIR, 'templates') を追加
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


# ★ここから書き換え
import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Render上でデータベースURLが設定されていたら、それを優先して使う
db_from_env = dj_database_url.config(conn_max_age=0)
DATABASES['default'].update(db_from_env)
# ★ここまで

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# ★日本語設定
LANGUAGE_CODE = 'ja'

# ★日本時間設定
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# ★静的ファイル（CSSなど）のURL
STATIC_URL = 'static/'

# ★静的ファイルを集める場所（PythonAnywhereで collectstatic するのに必須）
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Media files (User uploaded images)
# ★アップロードされた画像のURL
MEDIA_URL = '/media/'

# ★アップロードされた画像の保存場所
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ★Render用の設定
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'