# Generated by Django 6.0.1 on 2026-01-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='車種名')),
                ('price_vehicle', models.PositiveIntegerField(default=0, verbose_name='車両本体価格')),
                ('price_misc', models.PositiveIntegerField(default=0, verbose_name='諸費用')),
                ('price_total', models.PositiveIntegerField(default=0, verbose_name='支払総額')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='管理番号(SKU)')),
                ('is_new_arrival', models.BooleanField(default=True, verbose_name='新規入庫')),
                ('is_sold_out', models.BooleanField(default=False, verbose_name='SOLD OUT')),
                ('image_main', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='メイン画像')),
                ('registration_year', models.CharField(blank=True, max_length=50, verbose_name='初年度登録')),
                ('mileage', models.CharField(blank=True, max_length=50, verbose_name='走行距離')),
                ('inspection', models.CharField(blank=True, max_length=50, verbose_name='車検')),
                ('repair_history', models.CharField(choices=[('none', 'なし'), ('exist', 'あり')], default='none', max_length=10, verbose_name='修復歴')),
                ('body_color', models.CharField(blank=True, max_length=50, verbose_name='ボディカラー')),
                ('interior_color', models.CharField(blank=True, max_length=50, verbose_name='内装色')),
                ('handle', models.CharField(choices=[('right', '右'), ('left', '左')], default='right', max_length=10, verbose_name='ハンドル')),
                ('import_route', models.CharField(choices=[('dealer', 'ディーラー'), ('parallel', '並行')], default='dealer', max_length=20, verbose_name='輸入経路')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='全長(cm)')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='全幅(cm)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='全高(cm)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='車体重量(kg)')),
                ('length_width_height', models.CharField(blank=True, max_length=50, verbose_name='全長x全幅x全高(mm)')),
                ('wheelbase', models.IntegerField(blank=True, null=True, verbose_name='ホイールベース(mm)')),
                ('tread', models.CharField(blank=True, max_length=50, verbose_name='トレッド前/後(mm)')),
                ('min_turning_radius', models.FloatField(blank=True, null=True, verbose_name='最小回転半径(m)')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='生産国')),
                ('production_period', models.CharField(blank=True, max_length=50, verbose_name='生産期間')),
                ('new_car_price', models.CharField(blank=True, max_length=50, verbose_name='新車時車両価格')),
                ('model_code', models.CharField(blank=True, max_length=50, verbose_name='型式')),
                ('door_count', models.IntegerField(blank=True, null=True, verbose_name='ドア数')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='乗車定員')),
                ('seat_rows', models.IntegerField(blank=True, null=True, verbose_name='シート列数')),
                ('drive_system', models.CharField(blank=True, max_length=50, verbose_name='駆動方式')),
                ('transmission', models.CharField(blank=True, max_length=50, verbose_name='ミッション')),
                ('transmission_pos', models.CharField(blank=True, max_length=50, verbose_name='ミッション位置')),
                ('has_ai_shift', models.BooleanField(default=False, verbose_name='AI-SHIFT')),
                ('has_manual_mode', models.BooleanField(default=False, verbose_name='マニュアルモード')),
                ('comment', models.TextField(blank=True, verbose_name='商品コメント')),
                ('equipment_standard', models.TextField(blank=True, verbose_name='標準装備')),
                ('equipment_option', models.TextField(blank=True, verbose_name='オプション装備')),
                ('equipment_custom', models.TextField(blank=True, verbose_name='社外装備')),
                ('has_abs', models.BooleanField(default=False, verbose_name='ABS')),
                ('has_esc', models.BooleanField(default=False, verbose_name='ESC')),
                ('has_brake_assist', models.BooleanField(default=False, verbose_name='衝突被害軽減B')),
                ('has_acc', models.BooleanField(default=False, verbose_name='ACC')),
                ('has_camera_360', models.BooleanField(default=False, verbose_name='全周囲カメラ')),
                ('has_led', models.BooleanField(default=False, verbose_name='LEDライト')),
                ('has_power_gate', models.BooleanField(default=False, verbose_name='電動リアゲート')),
                ('has_sunroof', models.BooleanField(default=False, verbose_name='サンルーフ')),
                ('has_leather_seat', models.BooleanField(default=False, verbose_name='本革シート')),
                ('has_navi', models.BooleanField(default=False, verbose_name='ナビ・TV')),
                ('has_etc', models.BooleanField(default=False, verbose_name='ETC')),
                ('has_warranty', models.BooleanField(default=False, verbose_name='保証書')),
                ('has_manual', models.BooleanField(default=False, verbose_name='取説')),
                ('has_record', models.BooleanField(default=False, verbose_name='記録簿')),
                ('has_spare_key', models.BooleanField(default=False, verbose_name='スペアキー')),
                ('is_one_owner', models.BooleanField(default=False, verbose_name='ワンオーナー')),
                ('is_no_smoking', models.BooleanField(default=False, verbose_name='禁煙車')),
                ('document_notes', models.CharField(blank=True, max_length=200, verbose_name='書類備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
