# Generated by Django 6.0.1 on 2026-01-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='has_acc',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_brake_assist',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_led',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_navi',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_no_smoking',
        ),
        migrations.AddField(
            model_name='car',
            name='has_4wd',
            field=models.BooleanField(default=False, verbose_name='4WD'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_aero_parts',
            field=models.BooleanField(default=False, verbose_name='エアロパーツ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_aftermarket_muffler',
            field=models.BooleanField(default=False, verbose_name='社外マフラー'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_air_suspension',
            field=models.BooleanField(default=False, verbose_name='エアサスペンション'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_airbag',
            field=models.BooleanField(default=False, verbose_name='エアバック'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_aircon',
            field=models.BooleanField(default=False, verbose_name='エアコン'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_aluminum_wheel',
            field=models.BooleanField(default=False, verbose_name='アルミホイール'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_auto_highbeam',
            field=models.BooleanField(default=False, verbose_name='オートマチックハイビーム'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_auto_light',
            field=models.BooleanField(default=False, verbose_name='オートライト'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_auto_parking',
            field=models.BooleanField(default=False, verbose_name='自動駐車システム'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_back_camera',
            field=models.BooleanField(default=False, verbose_name='バックカメラ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_bluetooth',
            field=models.BooleanField(default=False, verbose_name='Bluetooth接続'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_cd',
            field=models.BooleanField(default=False, verbose_name='CD'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_clearance_sonar',
            field=models.BooleanField(default=False, verbose_name='クリアランスソナー'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_collision_safety',
            field=models.BooleanField(default=False, verbose_name='衝突被害軽減システム'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_cruise_control',
            field=models.BooleanField(default=False, verbose_name='クルーズコントロール'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_diesel',
            field=models.BooleanField(default=False, verbose_name='ディーゼル'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_downhill_assist',
            field=models.BooleanField(default=False, verbose_name='ダウンヒルアシスト'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_drive_recorder',
            field=models.BooleanField(default=False, verbose_name='ドライブレコーダー'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_dvd',
            field=models.BooleanField(default=False, verbose_name='DVD'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_electric_mirror',
            field=models.BooleanField(default=False, verbose_name='電動格納ミラー'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_fog_lamp',
            field=models.BooleanField(default=False, verbose_name='フォグランプ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_front_camera',
            field=models.BooleanField(default=False, verbose_name='フロントカメラ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_full_aero',
            field=models.BooleanField(default=False, verbose_name='フルエアロ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_fullseg_tv',
            field=models.BooleanField(default=False, verbose_name='フルセグTV'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_half_leather',
            field=models.BooleanField(default=False, verbose_name='ハーフ レザーシート'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_hdd_navi',
            field=models.BooleanField(default=False, verbose_name='HDDナビ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_hid_headlight',
            field=models.BooleanField(default=False, verbose_name='HIDヘッドライト'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_keyless',
            field=models.BooleanField(default=False, verbose_name='キーレスエントリー'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_lane_assist',
            field=models.BooleanField(default=False, verbose_name='レーンアシスト'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_led_headlight',
            field=models.BooleanField(default=False, verbose_name='LEDヘッドライト'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_lift_up',
            field=models.BooleanField(default=False, verbose_name='リフトアップ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_low_down',
            field=models.BooleanField(default=False, verbose_name='ローダウン'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_maintenance_note',
            field=models.BooleanField(default=False, verbose_name='整備手帳'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_memory_navi',
            field=models.BooleanField(default=False, verbose_name='メモリーナビ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_music_player_connect',
            field=models.BooleanField(default=False, verbose_name='ミュージックプレイヤー接続'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_music_server',
            field=models.BooleanField(default=False, verbose_name='ミュージックサーバー'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_park_assist',
            field=models.BooleanField(default=False, verbose_name='パークアシスト'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_power_seat',
            field=models.BooleanField(default=False, verbose_name='パワーシート'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_power_steering',
            field=models.BooleanField(default=False, verbose_name='パワーステアリング'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_power_window',
            field=models.BooleanField(default=False, verbose_name='パワーウィンドウ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_rear_monitor',
            field=models.BooleanField(default=False, verbose_name='後席モニター'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_runflat_tire',
            field=models.BooleanField(default=False, verbose_name='ランフラットタイヤ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_seat_aircon',
            field=models.BooleanField(default=False, verbose_name='シートエアコン'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_seat_heater',
            field=models.BooleanField(default=False, verbose_name='シートヒーター'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_side_camera',
            field=models.BooleanField(default=False, verbose_name='サイドカメラ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_smart_key',
            field=models.BooleanField(default=False, verbose_name='スマートキー'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_theft_prevention',
            field=models.BooleanField(default=False, verbose_name='盗難防止システム'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_usb_input',
            field=models.BooleanField(default=False, verbose_name='USB入力端子'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_system',
            field=models.CharField(blank=True, max_length=50, verbose_name='駆動方式(テキスト)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment_custom',
            field=models.TextField(blank=True, verbose_name='社外装備(自由入力)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment_option',
            field=models.TextField(blank=True, verbose_name='オプション装備(自由入力)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment_standard',
            field=models.TextField(blank=True, verbose_name='標準装備(自由入力)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_leather_seat',
            field=models.BooleanField(default=False, verbose_name='革シート'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_manual',
            field=models.BooleanField(default=False, verbose_name='取扱説明書'),
        ),
    ]
