# Generated by Django 6.0.1 on 2026-01-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_has_acc_remove_car_has_brake_assist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='length_width_height',
        ),
    ]
