# Generated by Django 6.0.1 on 2026-01-30 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_length_width_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='動画のURLを貼り付けてください', null=True, verbose_name='YouTube動画URL'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_system',
            field=models.CharField(blank=True, max_length=50, verbose_name='駆動方式'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment_custom',
            field=models.TextField(blank=True, verbose_name='社外装備'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment_option',
            field=models.TextField(blank=True, verbose_name='オプション装備'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment_standard',
            field=models.TextField(blank=True, verbose_name='標準装備'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_aero_parts',
            field=models.BooleanField(default=False, verbose_name='エアロ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_air_suspension',
            field=models.BooleanField(default=False, verbose_name='エアサス'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_auto_highbeam',
            field=models.BooleanField(default=False, verbose_name='オートハイビーム'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_auto_parking',
            field=models.BooleanField(default=False, verbose_name='自動駐車'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_back_camera',
            field=models.BooleanField(default=False, verbose_name='Bカメラ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_bluetooth',
            field=models.BooleanField(default=False, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_clearance_sonar',
            field=models.BooleanField(default=False, verbose_name='ソナー'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_collision_safety',
            field=models.BooleanField(default=False, verbose_name='衝突軽減'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_cruise_control',
            field=models.BooleanField(default=False, verbose_name='クルコン'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_downhill_assist',
            field=models.BooleanField(default=False, verbose_name='ダウンヒル'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_drive_recorder',
            field=models.BooleanField(default=False, verbose_name='ドラレコ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_fog_lamp',
            field=models.BooleanField(default=False, verbose_name='フォグ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_front_camera',
            field=models.BooleanField(default=False, verbose_name='Fカメラ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_half_leather',
            field=models.BooleanField(default=False, verbose_name='ハーフレザー'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_hid_headlight',
            field=models.BooleanField(default=False, verbose_name='HID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_keyless',
            field=models.BooleanField(default=False, verbose_name='キーレス'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_led_headlight',
            field=models.BooleanField(default=False, verbose_name='LED'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_music_player_connect',
            field=models.BooleanField(default=False, verbose_name='音楽再生接続'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_music_server',
            field=models.BooleanField(default=False, verbose_name='MSV'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_power_gate',
            field=models.BooleanField(default=False, verbose_name='電動ゲート'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_power_steering',
            field=models.BooleanField(default=False, verbose_name='パワステ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_power_window',
            field=models.BooleanField(default=False, verbose_name='Pウィンドウ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_runflat_tire',
            field=models.BooleanField(default=False, verbose_name='ランフラット'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_seat_aircon',
            field=models.BooleanField(default=False, verbose_name='ベンチレーション'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_seat_heater',
            field=models.BooleanField(default=False, verbose_name='ヒーター'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_side_camera',
            field=models.BooleanField(default=False, verbose_name='Sカメラ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_theft_prevention',
            field=models.BooleanField(default=False, verbose_name='盗難防止'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_usb_input',
            field=models.BooleanField(default=False, verbose_name='USB'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/sub/', verbose_name='画像')),
                ('category', models.CharField(choices=[('exterior', '外装'), ('interior', '内装'), ('other', 'その他')], default='exterior', max_length=10, verbose_name='カテゴリ')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
    ]
