# Generated by Django 6.0.1 on 2026-01-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_youtube_url_alter_car_drive_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image_main',
        ),
    ]
