# Generated by Django 6.0.1 on 2026-01-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dummy_trigger',
            field=models.ImageField(blank=True, null=True, upload_to='temp/', verbose_name='システム用(触らない)'),
        ),
    ]
