# Generated by Django 6.0.1 on 2026-02-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_dummy_trigger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_one_owner',
            new_name='has_one_owner',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='has_record',
            new_name='has_record_book',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='has_maintenance_note',
            new_name='has_service_record',
        ),
        migrations.RemoveField(
            model_name='car',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='car',
            name='country',
        ),
        migrations.RemoveField(
            model_name='car',
            name='document_notes',
        ),
        migrations.RemoveField(
            model_name='car',
            name='door_count',
        ),
        migrations.RemoveField(
            model_name='car',
            name='dummy_trigger',
        ),
        migrations.RemoveField(
            model_name='car',
            name='handle',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_4wd',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_aftermarket_muffler',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_ai_shift',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_air_suspension',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_auto_highbeam',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_auto_light',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_cd',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_clearance_sonar',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_diesel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_downhill_assist',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_drive_recorder',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_electric_mirror',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_fog_lamp',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_front_camera',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_full_aero',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_half_leather',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_manual_mode',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_music_player_connect',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_rear_monitor',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_runflat_tire',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_seat_aircon',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_side_camera',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_theft_prevention',
        ),
        migrations.RemoveField(
            model_name='car',
            name='height',
        ),
        migrations.RemoveField(
            model_name='car',
            name='import_route',
        ),
        migrations.RemoveField(
            model_name='car',
            name='interior_color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='length',
        ),
        migrations.RemoveField(
            model_name='car',
            name='min_turning_radius',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model_code',
        ),
        migrations.RemoveField(
            model_name='car',
            name='new_car_price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='production_period',
        ),
        migrations.RemoveField(
            model_name='car',
            name='seat_rows',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission_pos',
        ),
        migrations.RemoveField(
            model_name='car',
            name='tread',
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='car',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='car',
            name='wheelbase',
        ),
        migrations.RemoveField(
            model_name='car',
            name='width',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='category',
        ),
        migrations.AddField(
            model_name='carimage',
            name='image_type',
            field=models.CharField(choices=[('exterior', '外装'), ('interior', '内装'), ('other', 'その他')], default='exterior', max_length=20, verbose_name='写真種別'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_color',
            field=models.CharField(max_length=50, verbose_name='ボディカラー'),
        ),
        migrations.AlterField(
            model_name='car',
            name='comment',
            field=models.TextField(blank=True, verbose_name='車両詳細コメント'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='駆動方式'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment_custom',
            field=models.TextField(blank=True, verbose_name='カスタム装備(詳細)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment_option',
            field=models.TextField(blank=True, verbose_name='オプション装備(詳細)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment_standard',
            field=models.TextField(blank=True, verbose_name='標準装備(詳細)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_aero_parts',
            field=models.BooleanField(default=False, verbose_name='エアロパーツ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_auto_parking',
            field=models.BooleanField(default=False, verbose_name='自動駐車システム'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_back_camera',
            field=models.BooleanField(default=False, verbose_name='バックカメラ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_bluetooth',
            field=models.BooleanField(default=False, verbose_name='Bluetooth接続'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_collision_safety',
            field=models.BooleanField(default=False, verbose_name='衝突被害軽減ブレーキ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_cruise_control',
            field=models.BooleanField(default=False, verbose_name='クルーズコントロール'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_dvd',
            field=models.BooleanField(default=False, verbose_name='DVD再生'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_esc',
            field=models.BooleanField(default=False, verbose_name='ESC(横滑り防止)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_hid_headlight',
            field=models.BooleanField(default=False, verbose_name='HIDヘッドライト'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_led_headlight',
            field=models.BooleanField(default=False, verbose_name='LEDヘッドライト'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_music_server',
            field=models.BooleanField(default=False, verbose_name='ミュージックサーバー'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_power_gate',
            field=models.BooleanField(default=False, verbose_name='電動リアゲート'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_power_window',
            field=models.BooleanField(default=False, verbose_name='パワーウィンドウ'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_seat_heater',
            field=models.BooleanField(default=False, verbose_name='シートヒーター'),
        ),
        migrations.AlterField(
            model_name='car',
            name='has_usb_input',
            field=models.BooleanField(default=False, verbose_name='USB入力端子'),
        ),
        migrations.AlterField(
            model_name='car',
            name='inspection',
            field=models.CharField(max_length=50, verbose_name='車検'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_new_arrival',
            field=models.BooleanField(default=False, verbose_name='新規入庫'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=20, verbose_name='走行距離'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_misc',
            field=models.PositiveIntegerField(verbose_name='諸費用'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_total',
            field=models.PositiveIntegerField(verbose_name='支払総額(税込)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_vehicle',
            field=models.PositiveIntegerField(verbose_name='車両本体価格'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_year',
            field=models.CharField(max_length=20, verbose_name='年式'),
        ),
        migrations.AlterField(
            model_name='car',
            name='repair_history',
            field=models.CharField(choices=[('あり', 'あり'), ('なし', 'なし')], default='なし', max_length=20, verbose_name='修復歴'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='管理番号'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=100, verbose_name='車名'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='AT', max_length=50, verbose_name='ミッション'),
        ),
        migrations.AlterField(
            model_name='car',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/sub/'),
        ),
    ]
