# Generated by Django 6.0.1 on 2026-02-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_is_one_owner_car_has_one_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.CharField(blank=True, max_length=20, verbose_name='乗車定員'),
        ),
        migrations.AddField(
            model_name='car',
            name='door_count',
            field=models.CharField(blank=True, max_length=20, verbose_name='ドア数'),
        ),
        migrations.AddField(
            model_name='car',
            name='four_ws_status',
            field=models.CharField(blank=True, default='△', max_length=10, verbose_name='4WS'),
        ),
        migrations.AddField(
            model_name='car',
            name='handle',
            field=models.CharField(choices=[('右', '右'), ('左', '左')], default='右', max_length=20, verbose_name='ハンドル'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_ai_shift',
            field=models.BooleanField(default=False, verbose_name='AI-SHIFT'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_manual_mode',
            field=models.BooleanField(default=False, verbose_name='マニュアルモード'),
        ),
        migrations.AddField(
            model_name='car',
            name='height',
            field=models.CharField(blank=True, max_length=20, verbose_name='全高(cm)'),
        ),
        migrations.AddField(
            model_name='car',
            name='import_route',
            field=models.CharField(choices=[('ディーラー車', 'ディーラー車'), ('並行輸入車', '並行輸入車')], default='ディーラー車', max_length=50, verbose_name='輸入経路'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='内装色'),
        ),
        migrations.AddField(
            model_name='car',
            name='length',
            field=models.CharField(blank=True, max_length=20, verbose_name='全長(cm)'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='型式'),
        ),
        migrations.AddField(
            model_name='car',
            name='new_car_price',
            field=models.CharField(blank=True, max_length=50, verbose_name='新車時車両価格'),
        ),
        migrations.AddField(
            model_name='car',
            name='production_country',
            field=models.CharField(blank=True, max_length=50, verbose_name='生産国'),
        ),
        migrations.AddField(
            model_name='car',
            name='production_period',
            field=models.CharField(blank=True, max_length=50, verbose_name='生産期間'),
        ),
        migrations.AddField(
            model_name='car',
            name='seat_rows',
            field=models.CharField(blank=True, max_length=20, verbose_name='シート列数'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_pos',
            field=models.CharField(blank=True, max_length=50, verbose_name='ミッション位置'),
        ),
        migrations.AddField(
            model_name='car',
            name='tread_front',
            field=models.CharField(blank=True, max_length=20, verbose_name='前トレッド(mm)'),
        ),
        migrations.AddField(
            model_name='car',
            name='tread_rear',
            field=models.CharField(blank=True, max_length=20, verbose_name='後トレッド(mm)'),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.CharField(blank=True, max_length=20, verbose_name='車体重量(kg)'),
        ),
        migrations.AddField(
            model_name='car',
            name='wheelbase',
            field=models.CharField(blank=True, max_length=20, verbose_name='ホイールベース(mm)'),
        ),
        migrations.AddField(
            model_name='car',
            name='width',
            field=models.CharField(blank=True, max_length=20, verbose_name='全幅(cm)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_system',
            field=models.CharField(blank=True, default='4WD', max_length=50, null=True, verbose_name='駆動方式'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=50, verbose_name='走行距離'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_year',
            field=models.CharField(max_length=50, verbose_name='年式(初年度登録)'),
        ),
    ]
