# Generated by Django 6.0.1 on 2026-03-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_capacity_car_door_count_car_four_ws_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='has_4wd_check',
            field=models.BooleanField(default=False, verbose_name='4WD(チェックボックス)'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_auto_highbeam',
            field=models.BooleanField(default=False, verbose_name='オートマチックハイビーム'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_auto_light',
            field=models.BooleanField(default=False, verbose_name='オートライト'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_cd',
            field=models.BooleanField(default=False, verbose_name='CD再生'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_custom_muffler',
            field=models.BooleanField(default=False, verbose_name='社外マフラー'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_diesel',
            field=models.BooleanField(default=False, verbose_name='ディーゼル'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_fog_lamp',
            field=models.BooleanField(default=False, verbose_name='フォグランプ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_full_aero',
            field=models.BooleanField(default=False, verbose_name='フルエアロ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_half_leather_seat',
            field=models.BooleanField(default=False, verbose_name='ハーフレザーシート'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_music_player',
            field=models.BooleanField(default=False, verbose_name='ミュージックプレイヤー接続'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_rear_monitor',
            field=models.BooleanField(default=False, verbose_name='後席モニター'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_runflat_tire',
            field=models.BooleanField(default=False, verbose_name='ランフラットタイヤ'),
        ),
        migrations.AddField(
            model_name='car',
            name='has_seat_aircon',
            field=models.BooleanField(default=False, verbose_name='シートエアコン'),
        ),
    ]
