# Generated by Django 6.0.1 on 2026-03-12 09:01

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_has_4wd_check_car_has_auto_highbeam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='image_type',
        ),
        migrations.AddField(
            model_name='carimage',
            name='category',
            field=models.CharField(choices=[('exterior', '外装'), ('interior', '内装')], default='exterior', max_length=20, verbose_name='画像カテゴリー'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
