# Generated by Django 6.0.1 on 2026-03-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_carimage_image_type_carimage_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='carimage',
            name='image_type',
            field=models.CharField(default='exterior', max_length=20),
        ),
    ]
