# Generated by Django 6.0.1 on 2026-04-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_carimage_category_remove_carimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='公開する（チェックで本番表示）'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='car_images/', verbose_name='画像ファイル'),
        ),
    ]
