# Generated by Django 6.0.1 on 2026-04-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='ユーザーの質問')),
                ('ai_response', models.TextField(blank=True, null=True, verbose_name='AIの回答')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='添付ファイルURL')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='セッションID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
            ],
            options={
                'verbose_name': 'チャット履歴',
                'verbose_name_plural': 'チャット履歴一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
